name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 22.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 22.2.0
        cache: 'npm'
    - run: npm run install-deps
    - run: npm run compile
    - run: npm run export-satisfactory-data
    - run: npm run build-app

    - name: Deploy with gh-pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
